MyTravelCMS/Models/Traveller.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyTravelCMS.Models
{
    public class Traveller
    {
        [Key]
        public int TravellerID { get; set; }

        [Required, StringLength(255), Display(Name = "Name")]
        public string TravellerName { get; set; }

        [StringLength(int.MaxValue), Display(Name = "Bio")]
        public string TravellerBio { get; set; }

       
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<Tip> Tips { get; set; }
    }
}

MyTravelCMS/Controllers/TipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyTravelCMS.Models;
using MyTravelCMS.Models.ViewModels;
using System.IO; 

namespace MyTravelCMS.Controllers
{
    public class TipController : Controller
    {
        private TravelCMSContext db = new TravelCMSContext();
        // GET: Tip
        public ActionResult Index()
        { //make List in view
            return RedirectToAction("List");         
        }

        public ActionResult New()
        {//this is to populate dropdown list
            TipEdit tipEditView = new TipEdit();
            tipEditView.Countries = db.Countries.ToList();
            tipEditView.Travellers = db.Travellers.ToList();

            return View(tipEditView);
        }

        [HttpPost]
        public ActionResult Create(string TipTitle_New, string TipContent_New, int TipTraveller_New, int? TipCountry_New)
        {
            string query = "insert into Tips (TipTitle, TipContent, HasImg, ImgType, Country_CountryID, Traveller_TravellerID ) " +
                "values (@title,@content, 0, 0, @cid, @tid)";

            SqlParameter[] myparams = {
            new SqlParameter("@title", TipTitle_New),
            new SqlParameter("@content", TipContent_New),
            new SqlParameter("@cid", TipCountry_New),
            new SqlParameter("@tid", TipTraveller_New)
        };
            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("List");
        }

        public ActionResult Details(int id)
        {//don't forget to make Details in view
            string query = "select * from tips where tipid =@id";

            return View(db.Tips.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }

        public ActionResult Edit(int? id)
        {
            //compound view         
            TipEdit tipEdit = new TipEdit();
            tipEdit.Tip = db.Tips.Find(id);
            tipEdit.Countries = db.Countries.ToList();
            tipEdit.Travellers = db.Travellers.ToList();
            if (tipEdit.Tip != null) return View(tipEdit);
            else return HttpNotFound();
        }
        //edit
        [HttpPost]
        public ActionResult Edit(int? id, string TipTitle, string TipContent, int? TipCountry, int? TipTraveller, HttpPostedFileBase tipImg)
        {
            if (tipImg != null || tipImg?.ContentLength > 0)
            {
                //this part adopted from inclass example 
                
                var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
                var extension = Path.GetExtension(tipImg.FileName).Substring(1);

                if (valtypes.Contains(extension))
                {
                    string imgStr = id + "." + extension;

                    string path = Path.Combine(Server.MapPath("~/images/UploadedFiles"), imgStr);

                    tipImg.SaveAs(path);

                    int HasImg = 1;
                    string ImgType = extension;

                    string pictureQuery = "update tips set HasImg=@hasImg, ImgType=@type where tipid=@id";
                    SqlParameter[] picParams = {
                     new SqlParameter("@hasImg", HasImg),
                     new SqlParameter("@type", ImgType),
                     new SqlParameter("@id", id)
                };
                    db.Database.ExecuteSqlCommand(pictureQuery, picParams);

                }
            }



            if ((id == null) || (db.Tips.Find(id) == null))
            {
                return HttpNotFound();

            }
          
            string query = "update tips set tiptitle=@title, " +
                "tipcontent=@content, " +
                "Country_CountryID=@cid, " + "Traveller_TravellerID=@tid where tipid = @id";
            SqlParameter[] parameters = new SqlParameter[5];
            
            parameters[0] = new SqlParameter("@title", TipTitle);
            parameters[1] = new SqlParameter("@content", TipContent);
            parameters[2] = new SqlParameter("@cid", TipCountry);
            parameters[3] = new SqlParameter("@tid", TipTraveller);
            parameters[4] = new SqlParameter("@id", id);

            
            
            db.Database.ExecuteSqlCommand(query, parameters);


            return RedirectToAction("Details/" + id);
        }
    
        public ActionResult Delete(int id)
        {
            string query = "delete from tips where TipID = @id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
             
            return RedirectToAction("List");

        }

        public ActionResult List()
        { 
            return View(db.Tips.ToList()); //IEnumerable<Tip> tips = db.Tips.ToList();
                                           //return View(tips); is the same/ to use it later in view IEnumerable<MyTravelCMS.Models.Tip>to print list of tips
        }
    }
}
//the code contains adopted and modified parts from inclass example as well as from online source https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/passing-arrays-as-arguments

MyTravelCMS/Controllers/TravellerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyTravelCMS.Models;
using System.Data.SqlClient;

namespace MyTravelCMS.Controllers
{
    public class TravellerController : Controller
    {
        private TravelCMSContext db = new TravelCMSContext();

        // GET: Traveller/List
        public ActionResult Index()
        {
            return RedirectToAction("List");
            //make List in view
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string travellerName, string travellerBio)
        {
            string query = "insert into Travellers (TravellerName, TravellerBio) " +
                "values (@name,@bio)";

            SqlParameter[] myparams = {
             new SqlParameter("@name", travellerName),
             new SqlParameter("@bio", travellerBio)
        };
            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            return View(db.Travellers.Find(id));
        }

        [HttpPost]
        public ActionResult Edit(int? id, string travellerName, string travellerBio)
        {
            if ((id == null) || (db.Travellers.Find(id) == null))
            {
                return HttpNotFound();

            }
            string query = "update travellers set TravellerName=@name, TravellerBio=@bio where travellerid=@id";
            SqlParameter[] myparams = {
             new SqlParameter("@name", travellerName),
             new SqlParameter("@bio", travellerBio),
             new SqlParameter("@id", id)
        };
             db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Index");

        }

        public ActionResult Details(int id)
        {
            return View(db.Travellers.Find(id));
        }

        public ActionResult Delete(int id)
        {
            //delete tips associated with the deleted traveller (referential integrity)
            string query = "delete from tips where Traveller_TravellerID=@id";
            SqlParameter parameter = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, parameter);

            query = "delete from travellers where TravellerID = @id";
            parameter = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, parameter);
            
            return RedirectToAction("List");

        }

        public ActionResult List()
        {
           
            return View(db.Travellers.ToList());

        }
    }
}
//the code may contain adopted and modified parts from inclass example as well as from online source https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/passing-arrays-as-arguments

MyTravelCMS/Views/Traveller/Details.cshtml
@model MyTravelCMS.Models.Traveller

@{
    ViewBag.Title = "Details";
}

<h2  style="font-family: 'Pacifico', cursive;">@Model.TravellerName</h2>
<p>@Model.TravellerBio</p>
<div class="btn btn-default pull-right">
    @Html.ActionLink("Edit the Traveller", "Edit/" + Model.TravellerID, "Traveller")
</div>

<div class="btn btn-default pull-right">
    @Html.ActionLink("Delete the Traveller", "Delete/" + Model.TravellerID, "Traveller")
</div>
<div>
    <h3>List of tips</h3>
    <div>
        @foreach (var tip in Model.Tips)
        {
        <div>
            @Html.ActionLink(tip.TipTitle, "Details/" + tip.TipID, "Tip")
        </div>
            }
    </div>
</div>

MyTravelCMS/Views/Traveller/Edit.cshtml
@model MyTravelCMS.Models.Traveller

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<form action="/Traveller/Edit/@Model.TravellerID" method="post">
    <div class="form-group">
        <label>Name:</label>
        <input type="text" name="travellerName" value="@Model.TravellerName" class="form-control" />
    </div>
    <div class="form-group">
        <label>Bio:</label>
        <textarea name="travellerBio" class="form-control">@Model.TravellerBio</textarea>
    </div>
    <input type="submit" name="submitBtn" />
</form>

MyTravelCMS/Views/Traveller/List.cshtml
@model IEnumerable<MyTravelCMS.Models.Traveller>

@{
    ViewBag.Title = "List";
}

<h2>Travelers</h2>

<div class="btn btn-default pull-right">
    @Html.ActionLink("Add New Traveler", "New", "Traveller")
</div>

@foreach(var traveller in Model)
    {
<div class="showlist" style="font-family: 'Open Sans', sans-serif;">
    @Html.ActionLink(traveller.TravellerName, "Details/" + traveller.TravellerID, "Traveller")
</div>
    }

MyTravelCMS/Views/Traveller/New.cshtml
@{
    ViewBag.Title = "New";
}

<h2>New Traveler :)</h2>
<form action="/Traveller/Create" method="post">
    <div class="form-group">
        <label>Name:</label>
        <input type="text" name="travellerName" class="form-control" />
    </div>
    <div class="form-group">
        <label>Bio:</label>
        <textarea  name="travellerBio" class="form-control"></textarea>
    </div>
    <div>
        <input type="submit" name="submitBtn" class="btn btn-default" />
    </div>
   
</form>